id: 01bb659aacda43f3955b1808eb8dadb2
title: Toh_270-The_Seven_Buddhas-v2
type: translation
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-068-004
  eft-text-version: 1.1.8 2020
